DROP TABLE TB_USER CASCADE CONSTRAINTS;
DROP TABLE TB_BOARD CASCADE CONSTRAINTS;
DROP TABLE TB_BOARD_CODE CASCADE CONSTRAINTS;

DROP SEQUENCE USER_SEQ;
DROP SEQUENCE BOARD_SEQ;

CREATE TABLE TB_USER(
      SEQ NUMBER NOT NULL,
      USER_ID VARCHAR2(20),
      PASSWORD VARCHAR2(20),
      EMAIL VARCHAR2(30),
      PHONE VARCHAR2(15),
      AGE NUMBER(3),
	JOINDATE DATE
);

alter table TB_USER add(picture varchar2(100));
desc TB_USER;


CREATE TABLE TB_BOARD(
          SEQ NUMBER NOT NULL,
          USER_ID VARCHAR2(20),
          TITLE VARCHAR2(255),
          CONTENTS VARCHAR2(4000),
		  BOARD_NAME VARCHAR2(30),   
          MODIFYDATE DATE
);

CREATE TABLE TB_BOARD_CODE(
	BOARD_CODE NUMBER NOT NULL,
	BOARD_NAME VARCHAR2(30)
);

ALTER TABLE TB_USER ADD CONSTRAINT user_id_pk PRIMARY KEY(USER_ID);
ALTER TABLE TB_BOARD ADD CONSTRAINT user_id_fk FOREIGN KEY(USER_ID) REFERENCES TB_USER(USER_ID);
ALTER TABLE TB_BOARD_CODE ADD CONSTRAINT board_name_fk FOREIGN KEY(BOARD_NAME) REFERENCES TB_BOARD(BOARD_NAME);

CREATE SEQUENCE USER_SEQ START WITH 0 INCREMENT BY 1 NOMAXVALUE MINVALUE 0;
CREATE SEQUENCE BOARD_SEQ START WITH 0 INCREMENT BY 1 NOMAXVALUE MINVALUE 0;

INSERT INTO TB_USER VALUES(USER_SEQ.NEXTVAL,'Admin','Admin','Admin@admin.com','010-1234-1234',99,sysdate);
commit;

insert into tb_board values(BOARD_SEQ.nextval,'user1','user1',' 1',sysdate);
commit;